# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\da-V7\OneDrive\Escritorio\PROYECT\AT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from memory_widget import PhysicalMemoryWidget, VirtualMemoryWidget

import sys  
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QDialog, QVBoxLayout, QListWidget, QMainWindow
from PyQt5.QtGui import QColor, QPalette, QFont
from PyQt5 import QtWidgets, QtCore, QtGui, Qt
import psutil

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TASK MASTER 😊")
        MainWindow.resize(970, 695)
        MainWindow.setStyleSheet("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QFrame\" name=\"frame\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>1</x>\n"
"     <y>1</y>\n"
"     <width>219</width>\n"
"     <height>739</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"autoFillBackground\">\n"
"    <bool>false</bool>\n"
"   </property>\n"
"   <property name=\"frameShape\">\n"
"    <enum>QFrame::StyledPanel</enum>\n"
"   </property>\n"
"   <property name=\"frameShadow\">\n"
"    <enum>QFrame::Raised</enum>\n"
"   </property>\n"
"   <widget class=\"QFrame\" name=\"frame_2\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>20</x>\n"
"      <y>10</y>\n"
"      <width>181</width>\n"
"      <height>51</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"frameShape\">\n"
"     <enum>QFrame::StyledPanel</enum>\n"
"    </property>\n"
"    <property name=\"frameShadow\">\n"
"     <enum>QFrame::Raised</enum>\n"
"    </property>\n"
"    <widget class=\"QLabel\" name=\"label_2\">\n"
"     <property name=\"geometry\">\n"
"      <rect>\n"
"       <x>40</x>\n"
"       <y>10</y>\n"
"       <width>131</width>\n"
"       <height>31</height>\n"
"      </rect>\n"
"     </property>\n"
"     <property name=\"sizeIncrement\">\n"
"      <size>\n"
"       <width>14</width>\n"
"       <height>14</height>\n"
"      </size>\n"
"     </property>\n"
"     <property name=\"contextMenuPolicy\">\n"
"      <enum>Qt::CustomContextMenu</enum>\n"
"     </property>\n"
"     <property name=\"layoutDirection\">\n"
"      <enum>Qt::LeftToRight</enum>\n"
"     </property>\n"
"     <property name=\"styleSheet\">\n"
"      <string notr=\"true\">/* Estilos generales */\n"
"body {\n"
"  font-family: Arial, sans-serif;\n"
"  background-color: #1d224a;\n"
"}\n"
"\n"
"h1 {\n"
"  color: #333333;\n"
"  font-size: 28px;\n"
"}\n"
"\n"
"p {\n"
"  color: #666666;\n"
"  font-size: 16px;\n"
"  line-height: 1.5;\n"
"}\n"
"\n"
"/* Estilos para enlaces */\n"
"a {\n"
"  color: #0077cc;\n"
"  text-decoration: none;\n"
"}\n"
"\n"
"a:hover {\n"
"  text-decoration: underline;\n"
"}\n"
"\n"
"/* Estilos para botones */\n"
".button {\n"
"  display: inline-block;\n"
"  background-color: #0077cc;\n"
"  color: #ffffff;\n"
"  padding: 10px 20px;\n"
"  border-radius: 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"}\n"
"\n"
".button:hover {\n"
"  background-color: #005fa3;\n"
"}\n"
"</string>\n"
"     </property>\n"
"     <property name=\"text\">\n"
"      <string>TASK MASTER</string>\n"
"     </property>\n"
"     <property name=\"textFormat\">\n"
"      <enum>Qt::PlainText</enum>\n"
"     </property>\n"
"     <property name=\"wordWrap\">\n"
"      <bool>false</bool>\n"
"     </property>\n"
"    </widget>\n"
"   </widget>\n"
"   <widget class=\"QFrame\" name=\"frame_3\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>0</x>\n"
"      <y>210</y>\n"
"      <width>221</width>\n"
"      <height>291</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"frameShape\">\n"
"     <enum>QFrame::StyledPanel</enum>\n"
"    </property>\n"
"    <property name=\"frameShadow\">\n"
"     <enum>QFrame::Raised</enum>\n"
"    </property>\n"
"    <widget class=\"QPushButton\" name=\"pushButton\">\n"
"     <property name=\"geometry\">\n"
"      <rect>\n"
"       <x>10</x>\n"
"       <y>10</y>\n"
"       <width>200</width>\n"
"       <height>50</height>\n"
"      </rect>\n"
"     </property>\n"
"     <property name=\"styleSheet\">\n"
"      <string notr=\"true\">.button {\n"
"  display: inline-block;\n"
"  background-color: #ff6f61;\n"
"  color: #ffffff;\n"
"  padding: 10px 20px;\n"
"  border-radius: 5px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  border: none;\n"
"  font-weight: bold;\n"
"  text-transform: uppercase;\n"
"  letter-spacing: 1px;\n"
"  transition: background-color 0.3s ease-in-out;\n"
"}\n"
"\n"
".button:hover {\n"
"  background-color: #ff934f;\n"
"}</string>\n"
"     </property>\n"
"     <property name=\"text\">\n"
"      <string>PROCESOS</string>\n"
"     </property>\n"
"    </widget>\n"
"    <widget class=\"QPushButton\" name=\"pushButton_2\">\n"
"     <property name=\"geometry\">\n"
"      <rect>\n"
"       <x>10</x>\n"
"       <y>80</y>\n"
"       <width>200</width>\n"
"       <height>50</height>\n"
"      </rect>\n"
"     </property>\n"
"     <property name=\"text\">\n"
"      <string>MEMORIA</string>\n"
"     </property>\n"
"    </widget>\n"
"    <widget class=\"QPushButton\" name=\"pushButton_3\">\n"
"     <property name=\"geometry\">\n"
"      <rect>\n"
"       <x>10</x>\n"
"       <y>150</y>\n"
"       <width>200</width>\n"
"       <height>50</height>\n"
"      </rect>\n"
"     </property>\n"
"     <property name=\"text\">\n"
"      <string>CPU</string>\n"
"     </property>\n"
"    </widget>\n"
"    <widget class=\"QPushButton\" name=\"pushButton_4\">\n"
"     <property name=\"geometry\">\n"
"      <rect>\n"
"       <x>10</x>\n"
"       <y>220</y>\n"
"       <width>200</width>\n"
"       <height>50</height>\n"
"      </rect>\n"
"     </property>\n"
"     <property name=\"text\">\n"
"      <string>DISCO</string>\n"
"     </property>\n"
"    </widget>\n"
"   </widget>\n"
"   <widget class=\"QTextEdit\" name=\"textEdit\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>10</x>\n"
"      <y>550</y>\n"
"      <width>201</width>\n"
"      <height>61</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"mouseTracking\">\n"
"     <bool>false</bool>\n"
"    </property>\n"
"    <property name=\"autoFillBackground\">\n"
"     <bool>false</bool>\n"
"    </property>\n"
"    <property name=\"html\">\n"
"     <string>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;\n"
"&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;\n"
"p, li { blue-space: pre-wrap; }\n"
"&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;&quot;&gt;\n"
"&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;interfaz hecha en QT designer con el fin de montarr el administrador de tareas del sitemas operativo&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</string>\n"
"    </property>\n"
"   </widget>\n"
"   <widget class=\"QPushButton\" name=\"pushButton_5\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>10</x>\n"
"      <y>630</y>\n"
"      <width>91</width>\n"
"      <height>41</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"text\">\n"
"     <string>CERRAR</string>\n"
"    </property>\n"
"   </widget>\n"
"   <widget class=\"QLabel\" name=\"label\">\n"
"    <property name=\"geometry\">\n"
"     <rect>\n"
"      <x>30</x>\n"
"      <y>180</y>\n"
"      <width>47</width>\n"
"      <height>13</height>\n"
"     </rect>\n"
"    </property>\n"
"    <property name=\"text\">\n"
"     <string>INICIO</string>\n"
"    </property>\n"
"   </widget>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 961, 671))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #1d224a, stop: 1 #1d224a);\n"
"}\n"
"\n"
"QTextEdit {\n"
"    font-family: \"Helvetica Neue\", sans-serif;\n"
"    color: #f2f2f2;\n"


"    border: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(-10, 0, 71, 71))
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(70, 20, 121, 31))
        self.label_10.setStyleSheet("QLabel {\n"
"    font-family: \"Helvetica Neue\", sans-serif;\n"
"    color: white;\n"
"    border:0.5px solid white;\n"
"    border-radius: 5px;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 140, 241, 301))
        self.frame_3.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #34375a, stop: 0 #060a2f,\n"
"                                stop: 1 #232751);\n"
"    border: 1px solid #060a2f;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"    font-family: \'Montserrat\', sans-serif;\n"
"    font-weight: 300;\n"
"    padding: 10px 20px 10px 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #232751;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                      stop: 0 #1e8ae9, stop: 1 #01f6fd);\n"
"    color: #232751;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 201, 50))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 201, 50))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 160, 201, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 230, 201, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(18, 88, 205, 54))
        self.frame_5.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(18, 18, 205, 54))
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(18, 158, 205, 54))
        self.frame_7.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(18, 228, 205, 54))
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(190, 31, 16, 27))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 25, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(190, 102, 16, 25))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 25, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 25, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(190, 172, 16, 25))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(190, 242, 16, 25))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(50, 240, 25, 31))
        self.label_8.setObjectName("label_8")
        self.frame_8.raise_()
        self.frame_7.raise_()
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_2.raise_()
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 600, 121, 31))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
" padding: 10px 10px;\n"
" border-radius: 10px;\n"
" border: 0;\n"
" background-color: rgb(255, 56, 86);\n"
" letter-spacing: 1.5px;\n"
" font-size: 13px;\n"


" color: hsl(0, 0%, 100%);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"}\n"
"\n"
"QPushButton:active {\n"
" background-color: rgb(255, 56, 86);\n"
" /*50, 168, 80*/\n"
 

"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(240, 90, 721, 581))
        self.frame_4.setStyleSheet("QFrame {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #0c173d, stop: 1 #232751);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 10, 701, 561))
        self.stackedWidget_2.setStyleSheet("border: 2px solid white;")
        self.stackedWidget_2.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}\n"
"")     

        "------------------------"
    #     # Configurar la ventana principal y el QStackedWidget
    #     # ...
        
    #     # Agregar una página al QStackedWidget
    #     self.page_0 = QtWidgets.QWidget()
    #     self.page_0.setObjectName("page_0")
    #     self.stackedWidget_2.addWidget(self.page_0)

    #     # Agregar una QTableWidget a la página
    #     self.table = QtWidgets.QTableWidget(self.page_0)
    #     self.table.setGeometry(QtCore.QRect(0, 5, 700, 600))
    #     self.table.setColumnCount(5) # Cambiar el número de columnas a 5
    #     self.table.setHorizontalHeaderLabels(['PID', 'Nombre', 'Memoria', 'CPU', 'Disco']) # Agregar encabezados para las nuevas columnas

    #     # Crear un temporizador para actualizar la información cada segundo
    #     self.timer = QtCore.QTimer()
    #     self.timer.timeout.connect(self.update_process_info)
    #     self.timer.start(1000)

    # def update_process_info(self):
    #     # Obtener una lista de todos los procesos en ejecución
    #     processes = psutil.process_iter(['pid', 'name', 'memory_info', 'cpu_percent', 'io_counters'])

    #     # Limpiar la tabla
    #     self.table.setRowCount(0)

    #     # Agregar información sobre cada proceso a la tabla
    #     for process in processes:
    #         row = self.table.rowCount()
    #         self.table.insertRow(row)
    #         self.table.setItem(row, 0, QtWidgets.QTableWidgetItem(str(process.info['pid'])))
    #         self.table.setItem(row, 1, QtWidgets.QTableWidgetItem(process.info['name']))
    #         memory_usage_mb = process.info['memory_info'].rss / (1024 * 1024)
    #         self.table.setItem(row, 2, QtWidgets.QTableWidgetItem(f'{memory_usage_mb:.1f} MB'))
    #         self.table.setItem(row, 3, QtWidgets.QTableWidgetItem(str(process.info['cpu_percent'])))
    #         if process.info['io_counters']:
    #             disk_usage_mb = (process.info['io_counters'].read_bytes + process.info['io_counters'].write_bytes) / (1024 * 1024)
    #             self.table.setItem(row, 4, QtWidgets.QTableWidgetItem(f'{disk_usage_mb:.1f} MB'))
                
    #     self.table.setStyleSheet("background-color: transparent; color: white;")
    #     header = self.table.horizontalHeader()
    #     header.setStyleSheet("QHeaderView::section {background-color: transparent;}")
    #     vertical_header = self.table.verticalHeader()
    #     vertical_header.setStyleSheet("QHeaderView::section {background-color: transparent;}")
    #     corner_button = self.table.findChild(QtWidgets.QAbstractButton)
    #     corner_button.setStyleSheet("background-color: transparent;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")

        self.graphicsView_1 = QtWidgets.QGraphicsView(self.page_0)
        self.graphicsView_1.setGeometry(QtCore.QRect(10, 10, 681, 291))
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.frame_15 = QtWidgets.QFrame(self.page_0)
        self.frame_15.setGeometry(QtCore.QRect(10, 310, 681, 241))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_3.addWidget(self.frame_16)
        self.frame_16_layout = QVBoxLayout(self.frame_16)

        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.stackedWidget_2.addWidget(self.page_0)

        self.graphicsView_1.setStyleSheet("border: 2px solid orange;")
        self.frame_15.setStyleSheet("border: 2px solid purple;")
        self.frame_16.setStyleSheet("border: 2px solid pink;")
        self.frame_17.setStyleSheet("border: 2px solid red;")
        "-----------------------"

        
    
        "-----------------------"
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")

        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.frame_18 = QtWidgets.QFrame(self.page_1)
        self.frame_18.setGeometry(QtCore.QRect(10, 310, 681, 241))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_18.setGeometry(QtCore.QRect(10, 310, 680, 240))

        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_4.addWidget(self.frame_19)
        self.frame_19_layout = QVBoxLayout(self.frame_19)
        self.frame_19_layout.setAlignment(QtCore.Qt.AlignLeft)
        self.memory_widget = PhysicalMemoryWidget()
        self.frame_19_layout.addWidget(self.memory_widget)
        
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.frame_20_layout = QVBoxLayout(self.frame_20)
        self.frame_20_layout.setAlignment(QtCore.Qt.AlignLeft)
        self.memory_widget = VirtualMemoryWidget()
        self.frame_20_layout.addWidget(self.memory_widget)
        self.horizontalLayout_4.addWidget(self.frame_20)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_1)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 10, 681, 291))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.stackedWidget_2.addWidget(self.page_1)

        self.frame_20.setStyleSheet("border: 2px solid color red;")
        self.frame_19.setStyleSheet("border: 2px solid color red;")
        self.frame_18.setStyleSheet("border: 2px solid color red;")
        "-----------------------------"

        "------------------------------"
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(20, 480, 191, 101))

        font = QtGui.QFont()
        font.setFamily("Dosis")
        font.setPointSize(12)

        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.graphicsView_2.setStyleSheet("border: 2px solid white;")
        self.label_11.setStyleSheet("QLabel {\n"
"    font-family: \"Dosis\", sans-serif;\n"
"    font-size: 14px;\n"
"    color: #cfcfcf;\n"
"    border: none;\n"
"}")
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 51, 16))
        self.label_12.setStyleSheet("QLabel {\n"
"    font-family: \"Dosis\", sans-serif;\n"
"    font-size: 15px;\n"
"    color: #cfcfcf;\n"
"    border: none;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 450, 161, 20))
        self.label_13.setStyleSheet("QLabel {\n"
"    font-family: \"Dosis\", sans-serif;\n"
"    font-size: 15px;\n"
"    color: #fff;\n"
"    border: none;\n"
"}")

        self.graphicsView_1 = QtWidgets.QGraphicsView(self.page_1)
        self.graphicsView_1.setGeometry(QtCore.QRect(10, 10, 681, 291))
        self.graphicsView_1.setObjectName("graphicsView_1")

        self.graphicsView_2.setStyleSheet("border: 2px solid white;")
        
        self.frame_15 = QtWidgets.QFrame(self.page_1)
        self.frame_15.setGeometry(QtCore.QRect(10, 310, 681, 241))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        "------------------------"
        
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")

        self.horizontalLayout_3.addWidget(self.frame_16)
        self.frame_16_layout = QVBoxLayout(self.frame_16)

        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")

        self.horizontalLayout_3.addWidget(self.frame_17)
        self.stackedWidget_2.addWidget(self.page_1)

        self.label_13.setObjectName("label_13")

        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(750, 10, 61, 71))
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(890, 20, 71, 61))
        self.label_15.setObjectName("label_15")

        self.frame_2.raise_()
        self.pushButton_5.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.graphicsView_2)
        MainWindow.setTabOrder(self.graphicsView_2, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.graphicsView_2)
    
        "-----------------------"
        self.page_2 = QWidget()
        self.page_2_layout = QVBoxLayout(self.page_2)
        self.stackedWidget_2.addWidget(self.page_2)

        self.graphicsView_1 = QGraphicsView(self.page_2)
        self.graphicsView_1.setGeometry(QtCore.QRect(10, 10, 681, 291))
        self.graphicsView_1.setObjectName("graphicsView_1")

        self.frame_50 = QFrame(self.page_2)
        self.frame_50.setGeometry(QtCore.QRect(10, 310, 681, 241))
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")

        self.horizontalLayout_3 = QHBoxLayout(self.frame_50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.frame_51 = QFrame(self.frame_50)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.horizontalLayout_3.addWidget(self.frame_51)

        self.frame_52 = QFrame(self.frame_51)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)

        # This line was commented out.
        # self.frame_52 = QtWidgets.QFrame(self.centralWidget)

        self.frame_52.setObjectName("frame_17")
        self.horizontalLayout_3.addWidget(self.frame_52)
        self.stackedWidget_2.addWidget(self.page_2)

        self.graphicsView_1.setStyleSheet("border: 2px solid orange;")
        self.frame_50.setStyleSheet("border: 2px solid purple;")
        self.frame_51.setStyleSheet("border: 2px solid pink;")

        # This line was missing the `self.` prefix.
        # frame_50.setStyleSheet("border: 2px solid red;")

        self.stacked_widget = QtWidgets.QStackedWidget()

        self.label = QLabel("Texto de prueba3333")
        self.frame_50.setLayout(self.frame_51_layout)
        self.frame_51.addWidget(self.label)

        "-----------------------"

        "-----------------------"
        self.stacked_widget = QtWidgets.QStackedWidget()
        self.page_3 = QtWidgets.QWidget()
        self.page_3_layout = QVBoxLayout(self.page_3)
        self.stackedWidget_2.addWidget(self.page_3)

        self.label = QtWidgets.QLabel("Texto de prueba4444")
        self.page_3_layout.addWidget(self.label)
        "-----------------------"

    def close_window(self):
        # Cierra la ventana principal
        self.close()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TASK MASTER 😊"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/letra-d.png\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">TASK MASTER</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Procesos"))
        self.pushButton.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(0))
        self.pushButton_2.setText(_translate("MainWindow", "Memoria"))
        self.pushButton_2.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(1))
        self.pushButton_3.setText(_translate("MainWindow", "CPU"))
        self.pushButton_3.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(2))
        self.pushButton_4.setText(_translate("MainWindow", "Disco "))
        self.pushButton_4.clicked.connect(lambda: self.stackedWidget_2.setCurrentIndex(3))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/angulo-derecho (2).png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/computadora.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/angulo-derecho (2).png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/upc.png\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/tablero (1).png\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/angulo-derecho (2).png\"/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/angulo-derecho (2).png\"/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/album.png\"/></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "CERRAR"))
        self.pushButton_5.clicked.connect(self.close_window)
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Puedes visualizar el uso de los recursos y los procesos de tu sistema y te permite modificarlos a tu gusto. Está hecha en Qt Designer, la mejor herramienta para crear interfaces gráficas.<br/></span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "INICIO"))
        self.label_13.setText(_translate("MainWindow", "Bienvenid@..."))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/avatar.png\"/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/icons/menu.png\"/></p></body></html>"))

import resource_rc

# Crear la aplicación y la ventana principal 

if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())